apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-usuarios
data:
  port: "8001"
  app_name: "ms-usuarios"
  db_host: "mysql8:3306"
  database: "ms-usuarios"
  #username: admin
  #password: password
  curso_url: "ms-cursos:8002"
  profile: "dev"
  lb_auth_issuer_uri: "http://127.0.0.1:9000"
  lb_usuarios_uri: "http://127.0.0.1:8001"
  application.yaml: |-
    config:
      texto: "Configurando ambiente por defecto"
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: "Configurando ambiente de desarrollo"
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: "Configurando ambiente de produccion"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-cursos
data:
  port: "8002"
  app_name: "ms-cursos"
  db_host: "postgres15:5432"
  database: "ms-cursos"
  #username: admin
  #password: password
  usuario_url: "ms-usuarios:8001"

