apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres15
          image: postgres:15.2-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: ms-cursos
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          hostPath:
            # localización del directorio en el host
            path: /var/lib/postgresql/data
            # este campo es opcional
            type: DirectoryOrCreate
