apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-usuarios

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-usuarios

  template:
    metadata:
      labels:
        app: ms-usuarios

    spec:
      containers:
      - image: camilomeneses/usuarios:latest
        name: usuarios
        ports:
        - containerPort: 8001
