apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-gateway
  template:
    metadata:
      labels:
        app: ms-gateway
    spec:
      containers:
        - image: camilomeneses/gateway:latest
          name: gateway
          ports:
            - containerPort: 8090