apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cursos
  template:
    metadata:
      labels:
        app: ms-cursos
    spec:
      containers:
        - name: cursos
          image: camilomeneses/cursos:latest
          ports:
            - containerPort: 8002
          env:
            - name: APP_NAME
              value: ms-cursos
            - name: PORT
              value: "8002"
            - name: DB_HOST
              value: "postgres15:5432"
            - name: DB_DATABASE
              value: ms-cursos
            - name: DB_USERNAME
              value: admin
            - name: DB_PASSWORD
              value: password
            - name: USUARIOS_URL
              value: "ms-usuarios:8001"