apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-cursos
  template:
    metadata:
      labels:
        app: ms-cursos
    spec:
      containers:
        - image: camilomeneses/cursos:latest
          name: cursos
          ports:
            - containerPort: 8002
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: app_name
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: database
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: password
            - name: USUARIOS_URL
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: usuario_url