apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-usuarios
  template:
    metadata:
      labels:
        app: ms-usuarios
    spec:
      containers:
        - image: camilomeneses/usuarios:latest
          name: usuarios
          ports:
            - containerPort: 8001
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios
                  key: app_name
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ms-usuarios
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-usuarios
                  key: password
            - name: CURSOS_URL
              valueFrom:
                configMapKeyRef:
                  name: ms-usuarios
                  key: curso_url