apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql8

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql8

  template:
    metadata:
      labels:
        app: mysql8

    spec:
      containers:
      - image: mysql:8
        name: mysql8
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: ms-usuarios
        volumeMounts:
          - name: data-mysql
            mountPath: /var/lib/mysql
      volumes:
        - name: data-mysql
          hostPath:
            # localización del directorio en el host
            path: /var/lib/mysql
            # este campo es opcional
            type: DirectoryOrCreate
