apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres15
          image: postgres:15.2-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: username

            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: password

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ms-cursos
                  key: database
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc