apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    # localización del directorio en el host
    path: /var/lib/postgresql/data
    # este campo es opcional
    type: DirectoryOrCreate