apiVersion: v1
kind: Secret
metadata:
  name: ms-usuarios
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: ms-cursos
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=